apiVersion: v1
kind: Deployment
metadata:
  name: filestoreserver
spec:
  containers:
    - name: fss
      image: <docker_hub_id>/image_name:tag
	  imagePullPolicy: Always
    
    resources:
	    limits:
		  cpu: 120m
		  memory: 500Mi
		requests:
		  cpu: 120m
		  memory: 500Mi
 
  